# Generated by Django 6.0 on 2025-12-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pumpcontrol',
            options={'verbose_name_plural': 'Pump Control'},
        ),
        migrations.AlterModelOptions(
            name='sensordata',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Sensor Data'},
        ),
        migrations.AlterField(
            model_name='pumpcontrol',
            name='override',
            field=models.BooleanField(default=False, help_text='If True, pump is manually controlled until override_until time'),
        ),
        migrations.AlterField(
            model_name='pumpcontrol',
            name='override_until',
            field=models.DateTimeField(blank=True, help_text='Override expires at this time. Null means indefinite override', null=True),
        ),
        migrations.AlterField(
            model_name='pumpcontrol',
            name='pump_status',
            field=models.BooleanField(default=False, help_text='Whether the pump is currently ON (True) or OFF (False)'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='moisture',
            field=models.FloatField(help_text='Soil moisture level in percentage (0-100%)'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='pump',
            field=models.BooleanField(default=False, help_text='Whether pump was running when this reading was taken'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Time when sensor reading was recorded'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['-timestamp'], name='api_sensord_timesta_95cb2f_idx'),
        ),
    ]
